from colorama import Fore, Style, Back
DISPLAY_WIDTH = 210
DISPLAY_HEIGHT = 50
# village macros
VILLAGE_WIDTH = 100
VILLAGE_HEIGHT = 50
BORDER_PIXEL = Back.WHITE + ' ' + Style.RESET_ALL
BACKGROUND_PIXEL = Back.GREEN + ' ' + Style.RESET_ALL
SCORECARD_PIXEL = Back.BLUE + ' ' + Style.RESET_ALL
RED_PIXEL = Back.RED + ' ' + Style.RESET_ALL
HUT = Back.LIGHTBLACK_EX + 'H' + Style.RESET_ALL
CANNON = Fore.RED + Back.LIGHTWHITE_EX + 'C' + Style.RESET_ALL
CANNON_SHOT = Fore.BLACK + Back.YELLOW + 'C' + Style.RESET_ALL
BARBARIAN_TILE = Fore.YELLOW + "B" + Style.RESET_ALL
ARCHER_TILE = Fore.YELLOW + "A" + Style.RESET_ALL
KING_TILE = Fore.RED + "K" + Style.RESET_ALL
QUEEN_TILE = Fore.RED+"Q"+Style.RESET_ALL
GRAVE_TILE = Fore.RED + "+" + Back.BLACK + Style.RESET_ALL
midCannon = Back.LIGHTMAGENTA_EX+Fore.BLACK+"C" + Style.RESET_ALL
CannonDead = Back.LIGHTRED_EX + Fore.BLACK+"C" + Style.RESET_ALL
WIZARD_HEALTH_25 = Back.LIGHTMAGENTA_EX + Fore.BLACK + "W"+Style.RESET_ALL
WIZARD_HEALTH_50 = Back.LIGHTRED_EX + Fore.BLACK + "W"+Style.RESET_ALL
WIZARD = Fore.RED + Back.LIGHTWHITE_EX + "W" + Style.RESET_ALL
WIZARD_SHOT = Fore.BLACK + Back.YELLOW + "W" + Style.RESET_ALL


# building coordinates
# store the top left corner baki can be done using manipulations
COORD_TOWN_HALL = (int(VILLAGE_HEIGHT/2), int(VILLAGE_WIDTH/2)-10)

# building health points
TOWN_HALL_HEALTH = 1000


# troops and spells
CAMP_SIZE = 12  # at max 20 soldiers
HEAL_SPELL = 2
RAGE_SPELL = 2
# tile map code
EMPTY = 0


# define the characters
KING = 'K'
QUEEN = 'Q'
KING_HEALTH_POINTS = 1000
QUEEN_HEALTH_POINTS = 1000
KING_DAMAGE = 30
QUEEN_DAMAGE = 30
KING_MOVEMENT_SPEED = 1
QUEEN_MOVEMENT_SPEED = 1
BARBARIAN = 'B'
BARBARIAN_HEALTH_POINTS = 100
BARBARIAN_DAMAGE = 20
BARBARIAN_MOVEMENT_SPEED = 1
CANNON_HEALTH_POINTS = 100
CANNON_DAMAGE = 20
CANNON_RADIUS = 5
ARCHER_ATTACK_RANGE = 5

# wizard tower
WIZARD_HEALTH = 100
WIZARD_DAMAGE = 10
# walls levels
WALL_LEVEL_1 = Back.YELLOW + Fore.BLACK + '*' + Style.RESET_ALL
WALL_LEVEL_2 = Back.MAGENTA + Fore.BLACK + '*' + Style.RESET_ALL
WALL_LEVEL_3 = Back.CYAN+Fore.BLACK + '*' + Style.RESET_ALL
# Health level
HWALL_LEVEL_1 = 40
HWALL_LEVEL_2 = 50
HWALL_LEVEL_3 = 60

# tile type
# empty tile
EMPTY = 0
# wall tile
TILE_WALL_LEVEL_1 = 1
TILE_WALL_LEVEL_2 = 2
TILE_WALL_LEVEL_3 = 3
TOWN_HALL = 4
HUT_TILE = 5
CANNON_TILE = 6
BARB = 7
WIZARD_TILE = 8
ARCH = 9
BALLOON = 10


# building colors
HIGH_HEALTH = Back.LIGHTGREEN_EX + ' ' + Style.RESET_ALL
MEDIUM_HEALTH = Back.LIGHTYELLOW_EX + ' ' + Style.RESET_ALL
LOW_HEALTH = Back.LIGHTRED_EX + ' ' + Style.RESET_ALL


# balloon
BALLOON_HEALTH = 100
BALLOON_DAMAGE = 30
BALLOON_MOVEMENT_SPEED = 2
BALLOON_TEXTURE = Fore.RED + Back.BLACK + "O" + Style.RESET_ALL
BALLOON_SHOT = Fore.RED + Back.GREEN + "O" + Style.RESET_ALL
